"""Initial database schema

Revision ID: 86aeafee1654
Revises:
Create Date: 2025-09-30 16:18:19.951541

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "86aeafee1654"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("clerk_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("organization_name", sa.String(length=255), nullable=True),
        sa.Column("preferences", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_clerk_id"), "users", ["clerk_id"], unique=True
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "activity_logs",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("resource_name", sa.String(length=255), nullable=True),
        sa.Column(
            "details", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "old_values", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "new_values", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_method", sa.String(length=10), nullable=True),
        sa.Column("request_path", sa.String(length=500), nullable=True),
        sa.Column("request_duration_ms", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_activity_action_created",
        "activity_logs",
        ["action", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_activity_resource",
        "activity_logs",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_index(
        "idx_activity_user_created",
        "activity_logs",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_logs_action"),
        "activity_logs",
        ["action"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_logs_id"), "activity_logs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_logs_resource_id"),
        "activity_logs",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_logs_resource_type"),
        "activity_logs",
        ["resource_type"],
        unique=False,
    )
    op.create_table(
        "coaches",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("current_club", sa.String(length=255), nullable=True),
        sa.Column("current_role", sa.String(length=100), nullable=True),
        sa.Column("coaching_level", sa.String(length=50), nullable=True),
        sa.Column("years_experience", sa.Integer(), nullable=True),
        sa.Column("contract_expires", sa.Date(), nullable=True),
        sa.Column("estimated_salary_eur", sa.Integer(), nullable=True),
        sa.Column("agent_name", sa.String(length=255), nullable=True),
        sa.Column(
            "agent_contact",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("preferred_formation", sa.String(length=20), nullable=True),
        sa.Column(
            "preferred_formations",
            postgresql.ARRAY(sa.String()),
            nullable=True,
        ),
        sa.Column(
            "tactical_style",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("coaching_philosophy", sa.Text(), nullable=True),
        sa.Column("leadership_style", sa.String(length=100), nullable=True),
        sa.Column("communication_style", sa.String(length=100), nullable=True),
        sa.Column(
            "coaching_metrics",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "team_performance",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "player_development",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "career_history",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "achievements",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "certifications", postgresql.ARRAY(sa.String()), nullable=True
        ),
        sa.Column(
            "languages_spoken", postgresql.ARRAY(sa.String()), nullable=True
        ),
        sa.Column("strengths", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("weaknesses", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "coaching_specialties",
            postgresql.ARRAY(sa.String()),
            nullable=True,
        ),
        sa.Column("scouting_notes", sa.Text(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("overall_rating", sa.Integer(), nullable=True),
        sa.Column("availability_status", sa.String(length=50), nullable=True),
        sa.Column("available_from_date", sa.Date(), nullable=True),
        sa.Column(
            "preferred_leagues", postgresql.ARRAY(sa.String()), nullable=True
        ),
        sa.Column(
            "salary_expectations",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "contract_preferences",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("data_source", sa.String(length=100), nullable=True),
        sa.Column("last_updated_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_coaches_formation_style",
        "coaches",
        ["preferred_formation", "leadership_style"],
        unique=False,
    )
    op.create_index(
        "idx_coaches_name_club",
        "coaches",
        ["name", "current_club"],
        unique=False,
    )
    op.create_index(
        "idx_coaches_nationality_experience",
        "coaches",
        ["nationality", "years_experience"],
        unique=False,
    )
    op.create_index(
        "idx_coaches_role_level",
        "coaches",
        ["current_role", "coaching_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_coaches_current_club"),
        "coaches",
        ["current_club"],
        unique=False,
    )
    op.create_index(
        op.f("ix_coaches_current_role"),
        "coaches",
        ["current_role"],
        unique=False,
    )
    op.create_index(op.f("ix_coaches_id"), "coaches", ["id"], unique=False)
    op.create_index(op.f("ix_coaches_name"), "coaches", ["name"], unique=False)
    op.create_index(
        op.f("ix_coaches_nationality"),
        "coaches",
        ["nationality"],
        unique=False,
    )
    op.create_index(
        op.f("ix_coaches_preferred_formation"),
        "coaches",
        ["preferred_formation"],
        unique=False,
    )
    op.create_table(
        "players",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("second_nationality", sa.String(length=100), nullable=True),
        sa.Column("height_cm", sa.Integer(), nullable=True),
        sa.Column("weight_kg", sa.Integer(), nullable=True),
        sa.Column("preferred_foot", sa.String(length=10), nullable=True),
        sa.Column("current_club", sa.String(length=255), nullable=True),
        sa.Column("position", sa.String(length=50), nullable=False),
        sa.Column(
            "secondary_positions", postgresql.ARRAY(sa.String()), nullable=True
        ),
        sa.Column("shirt_number", sa.Integer(), nullable=True),
        sa.Column("contract_expires", sa.Date(), nullable=True),
        sa.Column("market_value_eur", sa.Integer(), nullable=True),
        sa.Column("weekly_wage_eur", sa.Integer(), nullable=True),
        sa.Column("release_clause_eur", sa.Integer(), nullable=True),
        sa.Column("agent_name", sa.String(length=255), nullable=True),
        sa.Column(
            "agent_contact",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "current_season_stats",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "career_stats",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "performance_history",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "similarity_vector",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "performance_metrics",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "tactical_attributes",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("scouting_notes", sa.Text(), nullable=True),
        sa.Column("strengths", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("weaknesses", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("overall_rating", sa.Integer(), nullable=True),
        sa.Column("potential_rating", sa.Integer(), nullable=True),
        sa.Column("scout_rating", sa.Integer(), nullable=True),
        sa.Column("availability_status", sa.String(length=50), nullable=True),
        sa.Column("injury_status", sa.String(length=100), nullable=True),
        sa.Column("injury_return_date", sa.Date(), nullable=True),
        sa.Column("data_source", sa.String(length=100), nullable=True),
        sa.Column("data_quality_score", sa.Integer(), nullable=True),
        sa.Column("last_updated_by", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_players_age_position",
        "players",
        ["date_of_birth", "position"],
        unique=False,
    )
    op.create_index(
        "idx_players_market_value_desc",
        "players",
        [sa.literal_column("market_value_eur DESC")],
        unique=False,
    )
    op.create_index(
        "idx_players_name_club",
        "players",
        ["name", "current_club"],
        unique=False,
    )
    op.create_index(
        "idx_players_position_nationality",
        "players",
        ["position", "nationality"],
        unique=False,
    )
    op.create_index(
        op.f("ix_players_current_club"),
        "players",
        ["current_club"],
        unique=False,
    )
    op.create_index(op.f("ix_players_id"), "players", ["id"], unique=False)
    op.create_index(
        op.f("ix_players_market_value_eur"),
        "players",
        ["market_value_eur"],
        unique=False,
    )
    op.create_index(op.f("ix_players_name"), "players", ["name"], unique=False)
    op.create_index(
        op.f("ix_players_nationality"),
        "players",
        ["nationality"],
        unique=False,
    )
    op.create_index(
        op.f("ix_players_position"), "players", ["position"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column(
            "parameters",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "filters", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("template_id", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("file_format", sa.String(length=20), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "sections_included",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("generated_by", sa.UUID(), nullable=False),
        sa.Column(
            "shared_with",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("access_level", sa.String(length=20), nullable=True),
        sa.Column("generated_at", sa.String(length=255), nullable=True),
        sa.Column("expires_at", sa.String(length=255), nullable=True),
        sa.Column("download_count", sa.Integer(), nullable=True),
        sa.Column("last_downloaded_at", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("generation_time_seconds", sa.Integer(), nullable=True),
        sa.Column("data_points_included", sa.Integer(), nullable=True),
        sa.Column("version", sa.String(length=20), nullable=True),
        sa.Column("parent_report_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "access_level IN ('private', 'internal', 'public')",
            name="report_access_level_check",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'generating', 'completed', 'failed', 'expired')",
            name="report_status_check",
        ),
        sa.CheckConstraint(
            "type IN ('player_scout', 'coach_analysis', 'shortlist_summary', 'comparison', 'market_analysis')",
            name="report_type_check",
        ),
        sa.ForeignKeyConstraint(
            ["generated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_id"), "reports", ["id"], unique=False)
    op.create_index(
        op.f("ix_reports_status"), "reports", ["status"], unique=False
    )
    op.create_index(op.f("ix_reports_type"), "reports", ["type"], unique=False)
    op.create_table(
        "shortlists",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("shared_with", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("season", sa.String(length=20), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("budget_eur", sa.Integer(), nullable=True),
        sa.Column("max_budget_eur", sa.Integer(), nullable=True),
        sa.Column("target_count", sa.Integer(), nullable=True),
        sa.Column("completed_count", sa.Integer(), nullable=True),
        sa.Column("auto_update", sa.Boolean(), nullable=True),
        sa.Column("notifications_enabled", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "priority IN ('low', 'medium', 'high', 'urgent')",
            name="shortlist_priority_check",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived', 'completed', 'on_hold')",
            name="shortlist_status_check",
        ),
        sa.CheckConstraint(
            "type IN ('player', 'coach')", name="shortlist_type_check"
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shortlists_id"), "shortlists", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_shortlists_status"), "shortlists", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_shortlists_type"), "shortlists", ["type"], unique=False
    )
    op.create_table(
        "shortlist_items",
        sa.Column("shortlist_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("coach_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("strengths", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("weaknesses", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("fit_analysis", sa.Text(), nullable=True),
        sa.Column("scout_rating", sa.Integer(), nullable=True),
        sa.Column("technical_rating", sa.Integer(), nullable=True),
        sa.Column("personality_rating", sa.Integer(), nullable=True),
        sa.Column("overall_fit_rating", sa.Integer(), nullable=True),
        sa.Column("estimated_fee_eur", sa.Integer(), nullable=True),
        sa.Column("wage_demands_eur", sa.Integer(), nullable=True),
        sa.Column("total_cost_eur", sa.Integer(), nullable=True),
        sa.Column("contract_length_years", sa.Integer(), nullable=True),
        sa.Column(
            "contract_options",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("target_completion_date", sa.Date(), nullable=True),
        sa.Column("last_contacted_date", sa.Date(), nullable=True),
        sa.Column("next_action_date", sa.Date(), nullable=True),
        sa.Column("contact_attempts", sa.Integer(), nullable=True),
        sa.Column("meetings_held", sa.Integer(), nullable=True),
        sa.Column("offers_made", sa.Integer(), nullable=True),
        sa.Column(
            "agent_contact_info",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "club_contact_info",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "contact_history",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("added_by", sa.UUID(), nullable=True),
        sa.Column("last_updated_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('identified', 'scouted', 'analyzed', 'shortlisted', 'approached', 'negotiating', 'signed', 'rejected', 'unavailable')",
            name="shortlist_item_status_check",
        ),
        sa.CheckConstraint(
            "(player_id IS NOT NULL AND coach_id IS NULL) OR (player_id IS NULL AND coach_id IS NOT NULL)",
            name="shortlist_item_reference_check",
        ),
        sa.CheckConstraint(
            "priority >= 1 AND priority <= 5",
            name="shortlist_item_priority_check",
        ),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coaches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_updated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shortlist_id"],
            ["shortlists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "shortlist_id", "coach_id", name="unique_shortlist_coach"
        ),
        sa.UniqueConstraint(
            "shortlist_id", "player_id", name="unique_shortlist_player"
        ),
    )
    op.create_index(
        op.f("ix_shortlist_items_id"), "shortlist_items", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_shortlist_items_status"),
        "shortlist_items",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_shortlist_items_status"), table_name="shortlist_items"
    )
    op.drop_index(op.f("ix_shortlist_items_id"), table_name="shortlist_items")
    op.drop_table("shortlist_items")
    op.drop_index(op.f("ix_shortlists_type"), table_name="shortlists")
    op.drop_index(op.f("ix_shortlists_status"), table_name="shortlists")
    op.drop_index(op.f("ix_shortlists_id"), table_name="shortlists")
    op.drop_table("shortlists")
    op.drop_index(op.f("ix_reports_type"), table_name="reports")
    op.drop_index(op.f("ix_reports_status"), table_name="reports")
    op.drop_index(op.f("ix_reports_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_players_position"), table_name="players")
    op.drop_index(op.f("ix_players_nationality"), table_name="players")
    op.drop_index(op.f("ix_players_name"), table_name="players")
    op.drop_index(op.f("ix_players_market_value_eur"), table_name="players")
    op.drop_index(op.f("ix_players_id"), table_name="players")
    op.drop_index(op.f("ix_players_current_club"), table_name="players")
    op.drop_index("idx_players_position_nationality", table_name="players")
    op.drop_index("idx_players_name_club", table_name="players")
    op.drop_index("idx_players_market_value_desc", table_name="players")
    op.drop_index("idx_players_age_position", table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_coaches_preferred_formation"), table_name="coaches")
    op.drop_index(op.f("ix_coaches_nationality"), table_name="coaches")
    op.drop_index(op.f("ix_coaches_name"), table_name="coaches")
    op.drop_index(op.f("ix_coaches_id"), table_name="coaches")
    op.drop_index(op.f("ix_coaches_current_role"), table_name="coaches")
    op.drop_index(op.f("ix_coaches_current_club"), table_name="coaches")
    op.drop_index("idx_coaches_role_level", table_name="coaches")
    op.drop_index("idx_coaches_nationality_experience", table_name="coaches")
    op.drop_index("idx_coaches_name_club", table_name="coaches")
    op.drop_index("idx_coaches_formation_style", table_name="coaches")
    op.drop_table("coaches")
    op.drop_index(
        op.f("ix_activity_logs_resource_type"), table_name="activity_logs"
    )
    op.drop_index(
        op.f("ix_activity_logs_resource_id"), table_name="activity_logs"
    )
    op.drop_index(op.f("ix_activity_logs_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_action"), table_name="activity_logs")
    op.drop_index("idx_activity_user_created", table_name="activity_logs")
    op.drop_index("idx_activity_resource", table_name="activity_logs")
    op.drop_index("idx_activity_action_created", table_name="activity_logs")
    op.drop_table("activity_logs")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_clerk_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
